"""ProjectInterface ORM model — one row per port on a ProjectNode.

A node can have many interfaces (a router with 3 wires has 3 interfaces,
one per wire). An interface has:
  * a name (``eth0``, ``port1``, ``GigabitEthernet0/0``, …) — the
    user picks this
  * an IP address (nullable until the user types one)
  * a subnet mask (24, 30, etc.)
  * a MAC address (auto-generated by the backend at spawn time, in
    phase 02)

The "no templates" rule means interfaces are whatever the user types.
There is no convention like "router-1 always has eth0 = 10.0.0.1/24".
"""

from __future__ import annotations

import ipaddress
import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, ForeignKey, String, TypeDecorator
from sqlalchemy.dialects.postgresql import INET
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.host import Base

if TYPE_CHECKING:
    from app.models.project_node import ProjectNode
    from app.models.project_link import ProjectLink


# ─── ip_address column type ────────────────────────────────────────────
# We want this column to round-trip a plain Python ``str`` in the
# service code (so callers can ``iface.ip_address = "10.0.0.1"``)
# but the on-disk type is PostgreSQL INET, which needs a Python
# ``ipaddress.IPv4Address`` (or similar) on the bind side. Without
# this wrapper, asyncpg's INET codec throws ``InvalidTextRepresentation``
# on the INSERT.
#
# The wrapper:
#   • process_bind_param: converts str → IPv4Address on write
#   • process_result_value: converts IPv4Address (or str on refresh)
#     back to str on read
class _IPv4AddressINET(TypeDecorator):
    impl = INET
    cache_ok = True

    def process_bind_param(self, value, dialect):  # type: ignore[override]
        if value is None:
            return None
        if isinstance(value, str):
            return ipaddress.IPv4Address(value)
        return value

    def process_result_value(self, value, dialect):  # type: ignore[override]
        if value is None:
            return None
        if isinstance(value, (ipaddress.IPv4Address, ipaddress.IPv6Address)):
            return str(value)
        return str(value)


class ProjectInterface(Base):
    __tablename__ = "project_interfaces"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    node_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("project_nodes.id", ondelete="CASCADE"),
        index=True,
    )
    # User-typed port name. We don't constrain the format — "eth0",
    # "port1", "Gi0/0/0", "ens4" are all valid.
    name: Mapped[str] = mapped_column(String(50))
    # Nullable until the user types it. The frontend can validate
    # against the link's subnet once the user starts wiring. The
    # column type is a custom TypeDecorator around INET so the
    # service can keep passing a plain Python ``str``.
    ip_address: Mapped[str | None] = mapped_column(
        _IPv4AddressINET(), nullable=True
    )
    # Stored as a string ("/24", "/30") so the JSON serialisation is
    # trivial. The number form is in the same column — parsed by the
    # API layer.
    subnet_mask: Mapped[str | None] = mapped_column(String(5), nullable=True)
    # Auto-generated at spawn time. NULL until phase 02 spawns the
    # container and queries the kernel for the veth's MAC.
    mac_address: Mapped[str | None] = mapped_column(String(17), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=datetime.utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
    )

    # ── relationships ──────────────────────────────────────────────────
    node: Mapped["ProjectNode"] = relationship(back_populates="interfaces")
    # Links that reference this interface on either end. Used to
    # reject deletion of a wired interface with 409 Conflict.
    links_as_a: Mapped[list["ProjectLink"]] = relationship(
        "ProjectLink",
        foreign_keys="ProjectLink.iface_a_id",
        back_populates="iface_a",
    )
    links_as_b: Mapped[list["ProjectLink"]] = relationship(
        "ProjectLink",
        foreign_keys="ProjectLink.iface_b_id",
        back_populates="iface_b",
    )

    def __repr__(self) -> str:
        ip_part = f" {self.ip_address}{self.subnet_mask or ''}" if self.ip_address else ""
        return f"<ProjectInterface {self.name}{ip_part}>"
